[package]
name = "falda-superapp-desktop"
version = "1.0.0"
description = "Falda SuperApp Desktop Shell"
authors = ["you"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.0.0", features = [] }

[dependencies]
tauri = { version = "2.0.0", features = [] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
debug = 0
opt-level = 1
